import {StyleSheet, Dimensions} from 'react-native';

export default StyleSheet.create({
  ctaContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 40,
    margin: 16,
    borderWidth: 1,
    borderRadius: 8,
    flexDirection: 'row',
    paddingHorizontal: 16,
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
  },
  modalContainer: {
    height: 0.6 * Dimensions.get('window').height,
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 8,
    paddingBottom: 0,
    margin: 24,
  },
  title: {marginBottom: 16, fontWeight: 'bold'},
  description: {opacity: 0.7, marginBottom: 16},
  pickerItem: {
    flex: 1,
    height: 40,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    borderWidth: 1,
  },
  value: {fontWeight: 'bold'},
  modalTitle: {marginLeft: 16, fontWeight: 'bold'},
  close: {height: 18, width: 18},
  titleContainer: {flexDirection: 'row', justifyContent: 'space-between'},
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  delete: {height: 16, width: 16},
  selectedOptionsContainer: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: 16,
  },
  chip: {
    borderWidth: 1,
    borderRadius: 13,
    height: 26,
    marginBottom: 16,
    marginHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  chipTitle: {marginHorizontal: 8},
  deleteBtn: {marginRight: 8},
});
